[package]
name = "samsung-mdc-rust"
description = "Implementation of Samsung MDC protocol in Rust"
author = "Baptiste Saclier <baptiste@plan-valley.com>"
license = "MIT"
version = "0.2.1"
edition = "2024"

[dependencies]
thiserror = "2.0"